### PR TITLE
Auto Refresh every 10 minutes

### PR DESCRIPTION
**Pull request by Sharkgamedev**
Automatically refreshes the image file every 10 minutes without a need to reload the page

### CODE REVIEW

**Comment by Sharkgamedev** [comment]
Nevermind, refreshing isn't working correctly (It's just refreshing the iframe not the whole page) attempts to refresh the whole page are blocked by CORS I guess tampermonkey scripts are not run on the same level as pure chrome extensions...

**Comment by Sharkgamedev** [comment]
Right now I try refreshing by changing the images src using a new version of the flag hosted by Flannel007#5046 on AWS so it has no TTL sent to the browser as well as utilising a cache buster clientside to make sure it's always new.

**Comment by DanFlannel** [comment]
Yeah the issue was most likely with the TTL for Github most likely is the root of the issue, idk what it is but for the raw AWS S3 links have 0 ttl so all it would have to done is to manually overwrite it

**Comment by Sharkgamedev** [comment]
Closing because of answer in stage

**Pull request closed without merging**
